tasks:
  - name: Setup
    init: pnpm install --frozen-lockfile

github:
  prebuilds:
    branches: true

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
