tasks:
  - name: Setup
    init: pnpm install --frozen-lockfile

github:
  prebuilds:
    branches: true

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint

ports:
  # This port for the Nextjs app needs to be public, otherwise the Supabase Realtime functionality is not working because it is using WS.
  - port: 3000
    visibility: public
