tasks:
  - name: Setup
    init: yarn install
    command: yarn disable-telemetry

github:
  prebuilds:
    branches: true

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - bradlc.vscode-tailwindcss

ports:
  # This port for the Nextjs app needs to be public, otherwise the Supabase Realtime functionality is not working because it is using WS.
  - port: 3000
    visibility: public
